# Generated by Django 3.1.1 on 2020-09-21 13:02

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurence',
            fields=[
                ('occurence_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('geographic_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('To Validate', 'To Validate'), ('Validated', 'Validated'), ('Solved', 'Solved')], max_length=18)),
                ('category', models.CharField(choices=[('Construction', 'Construction'), ('Special Event', 'Special Event'), ('Incident', 'Incident'), ('Weather Condition', 'Wheather Condition'), ('Road Condition', 'Road Condition')], max_length=18)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
