# Generated by Django 3.1.1 on 2020-09-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubiwhere_challenge_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurence',
            name='author',
        ),
        migrations.AlterField(
            model_name='occurence',
            name='state',
            field=models.CharField(choices=[('To Validate', 'To Validate'), ('Validated', 'Validated'), ('Solved', 'Solved')], default='To Validate', max_length=18),
        ),
    ]
