# Generated by Django 3.1.1 on 2020-09-23 15:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubiwhere_challenge_app', '0002_auto_20200922_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='category',
            field=models.CharField(blank=True, choices=[('Construction', 'Construction'), ('Special Event', 'Special Event'), ('Incident', 'Incident'), ('Weather Condition', 'Wheather Condition'), ('Road Condition', 'Road Condition')], max_length=18),
        ),
        migrations.AlterField(
            model_name='occurence',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='occurence',
            name='geographic_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
    ]
